services:
  - type: web
    name: parkease-backend
    env: node
    root: .
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: build
        sync: false
      - key: JWT_SECRET
        scope: build
        sync: false
      - key: PORT
        value: 5000
      - key: CLOUD_NAME
        scope: build
        sync: false
      - key: API_KEY
        scope: build
        sync: false
      - key: API_SECRET
        scope: build
        sync: false
